RapidContactTracer/Models/SeatingChart.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace RapidContactTracer.Models
{
    public class SeatingChart
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int ID { get; set; }
        public int SeatingID { get; set; }
        public string Email { get; set; }
        //public Boolean IsAffected { get; set; }
    }
    public class SeatingChartDBContext : DbContext
    {
        public DbSet<SeatingChart> SeatingCharts { get; set; }
    }
}

RapidContactTracer/Controllers/SeatingChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RapidContactTracer.Controllers
{
    public class SeatingChartController : Controller
    {
        // GET: SeatingChart
        public ActionResult Index()
        {
            return View();
        }
    }
}

RapidContactTracer/Controllers/SeatingChartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RapidContactTracer.Models;

namespace RapidContactTracer.Controllers
{
    public class SeatingChartsController : Controller
    {
        private SeatingChartDBContext db = new SeatingChartDBContext();

        // GET: SeatingCharts
        public ActionResult Index()
        {
            return View(db.SeatingCharts.ToList());
        }

        // GET: SeatingCharts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SeatingChart seatingChart = db.SeatingCharts.Find(id);
            if (seatingChart == null)
            {
                return HttpNotFound();
            }
            return View(seatingChart);
        }

        // GET: SeatingCharts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SeatingCharts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,SeatingID,Email")] SeatingChart seatingChart)
        {
            if (ModelState.IsValid)
            {
                db.SeatingCharts.Add(seatingChart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(seatingChart);
        }

        // GET: SeatingCharts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SeatingChart seatingChart = db.SeatingCharts.Find(id);
            if (seatingChart == null)
            {
                return HttpNotFound();
            }
            return View(seatingChart);
        }

        // POST: SeatingCharts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,SeatingID,Email")] SeatingChart seatingChart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(seatingChart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(seatingChart);
        }

        // GET: SeatingCharts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SeatingChart seatingChart = db.SeatingCharts.Find(id);
            if (seatingChart == null)
            {
                return HttpNotFound();
            }
            return View(seatingChart);
        }

        // POST: SeatingCharts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SeatingChart seatingChart = db.SeatingCharts.Find(id);
            db.SeatingCharts.Remove(seatingChart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RapidContactTracer/Views/SeatingCharts/Create.cshtml
@model RapidContactTracer.Models.SeatingChart

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SeatingChart</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SeatingID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SeatingID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SeatingID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "SeatingChart")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RapidContactTracer/Views/SeatingCharts/Delete.cshtml
@model RapidContactTracer.Models.SeatingChart

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SeatingChart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SeatingID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SeatingID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RapidContactTracer/Views/SeatingCharts/Details.cshtml
@model RapidContactTracer.Models.SeatingChart

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SeatingChart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SeatingID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SeatingID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RapidContactTracer/Views/SeatingCharts/Edit.cshtml
@model RapidContactTracer.Models.SeatingChart

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SeatingChart</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SeatingID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SeatingID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SeatingID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RapidContactTracer/Views/SeatingCharts/Index.cshtml
@model IEnumerable<RapidContactTracer.Models.SeatingChart>
@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div id="content">
                <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
                <h1>Seating Chart</h1>
                <hr>
            </div>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <style>

        .seat {
            height: 150px;
            width: 150px;
            border: 5px solid gray;
            cursor: pointer;
            background-color: black;
        }

        .walk {
            padding-left: 250px;
        }

        #board {
            background-color: gray;
            height: 150px;
            width: 550px;
            border: 5px solid gray;
            cursor: pointer;
        }
    </style>

</head>
<body>
    <div style="border:1px solid gray; width:130px;">
        <table>
            <tr>
                <td colspan="4"></td>
                <td><div class="board"></div></td>
            </tr>
            <tr>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td class="walk"></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
            </tr>
            <tr>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div> </td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td class="walk">  </td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
            </tr>
            <tr>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div> </td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td class="walk">  </td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
            </tr>
            <tr>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div> </td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td class="walk">  </td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
                <td><div id="leftbox"ondrop="drophere(event)"ondragover="allowdrophere(event)" class="seat"></div></td>
            </tr>
        </table>
        <table>
            <tr>
                <td colspan="4"></td>
                <td><div class="board"></div></td>
            </tr>
            <tr>
                @foreach (var item in Model)
                {
                    <td><div id="rightbox"draggable="true"ondragstart="startdrag(event)" class="seat">@Html.DisplayFor(modelItem => item.FirstName)</div></td>

                }
            </tr>
        </table>

    </div>
    <script>

        allSeats = document.querySelectorAll('.seat');
        for (var i = 0; i < allSeats.length; i++) {
            var seat = allSeats[i];
            seat.addEventListener('click', function () {
                var bgclr = this.style.backgroundColor;
                if (bgclr == 'red')
                    this.style.backgroundColor = 'black'
                else
                    this.style.backgroundColor = 'red'
            }, false);
        }

        function startdrag(e) {
            e.dataTransfer.setData("Text", e.target.id);
        }

        function allowdrophere(e) {
            e.preventDefault();
        }

        function drophere(e) {
            e.preventDefault();
            var data = e.dataTransfer.getData("Text");
            e.target.appendChild(document.getElementById(data));
        }

        function dofirst() {
            image = document.getElementById('rightbox');
            image.addEventListener("dragstart", startdrag, false);
            box = document.getElementById('leftbox');
            leftbox.addEventListener("dragover", allowdrophere, false);
            leftbox.addEventListener("drop", drophere, false);
        }

        function startdrag(e) {
            e.dataTransfer.setData("Text", e.target.id);
        }

        function allowdrophere(e) {
            e.preventDefault();
        }

        function drophere(e) {
            e.preventDefault();
            var data = e.dataTransfer.getData("Text");
            e.target.appendChild(document.getElementById(data));
        } 
    </script>
</body>
</html>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SeatingID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SeatingID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }
</table>